language: ruby
branches:
  only:
    - master
services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker build --no-cache -t cloudqq/docker-odoo .
  - docker tag cloudqq/docker-odoo:latest cloudqq/docker-odoo:v1
  - docker push cloudqq/docker-odoo
